CREATE TABLE IF NOT EXISTS "submitted_cases" (
  "id"               serial PRIMARY KEY,
  "sf_case_id"       text,
  "sf_case_number"   text,
  "sync_status"      text NOT NULL DEFAULT 'pending',
  "sync_error"       text,
  "synced_at"        timestamp,
  "record_type_id"   text,
  "record_type_name" text,
  "subject"          text NOT NULL,
  "description"      text,
  "priority"         text DEFAULT 'Medium',
  "status"           text DEFAULT 'New',
  "owner_id"         text,
  "owner_name"       text,
  "owner_type"       text,
  "contact_id"       text,
  "contact_name"     text,
  "account_id"       text,
  "account_name"     text,
  "custom_fields"    jsonb,
  "created_by_email" text NOT NULL,
  "created_at"       timestamp DEFAULT now() NOT NULL,
  "updated_at"       timestamp DEFAULT now() NOT NULL
);
