import { useAppContext } from '@/context/AppContext';
import { ScrollArea } from '@/components/ui/scroll-area';
import { curriculumWeeklyReviews, CONTENT_STATUS_CONFIG } from '@/data/curriculumData';
import { BarChart2, ArrowRight } from 'lucide-react';

export default function PennyWeeklyReviews() {
  const { setSelectedItem } = useAppContext();

  return (
    <ScrollArea className="h-full">
      <div className="p-6 max-w-5xl space-y-5">
        <div>
          <p className="text-[11px] font-bold uppercase tracking-widest text-muted-foreground/60 mb-1">Curriculum Studio — Penny Assets</p>
          <h1 className="text-3xl font-serif font-bold text-foreground">Weekly Reviews</h1>
          <p className="text-[13px] text-muted-foreground mt-1">
            Coach-facing weekly cohort summaries generated by Penny — learner progress, confidence flags, at-risk alerts,
            and upcoming module milestones. Delivered via Slack and the Coach Dashboard.
          </p>
        </div>
        <div className="grid gap-4">
          {curriculumWeeklyReviews.map(review => {
            const statusCfg = CONTENT_STATUS_CONFIG[review.status];
            return (
              <button
                key={review.id}
                onClick={() => setSelectedItem({ type: 'curriculumItem', id: review.id, data: review })}
                className="rounded-xl border border-border bg-white p-4 text-left hover:border-cyan-200 hover:shadow-sm transition-all"
              >
                <div className="flex items-start justify-between gap-3 mb-2">
                  <div className="flex items-center gap-2">
                    <BarChart2 className="w-4 h-4 text-cyan-600 shrink-0" />
                    <div>
                      <p className="text-[13px] font-bold text-foreground">{review.name}</p>
                      <p className="text-[11px] text-muted-foreground">
                        {review.program}
                        {review.weekNumber ? ` · Week ${review.weekNumber as number}` : ' · Template'}
                        {review.deliveredVia ? ` · ${review.deliveredVia as string}` : ''}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    <span className={`text-[10px] font-semibold border rounded-full px-2 py-0.5 ${statusCfg.cls}`}>{statusCfg.label}</span>
                    <ArrowRight className="w-3.5 h-3.5 text-muted-foreground" />
                  </div>
                </div>
                <p className="text-[12px] text-muted-foreground">{review.purpose}</p>
                {!!(review.sampleOutput) && (
                  <div className="mt-2 rounded bg-cyan-50 border border-cyan-100 px-3 py-2">
                    <p className="text-[10px] font-bold text-cyan-600 mb-0.5">SAMPLE OUTPUT</p>
                    <p className="text-[11px] text-foreground/80 italic">"{review.sampleOutput as string}"</p>
                  </div>
                )}
              </button>
            );
          })}
        </div>
      </div>
    </ScrollArea>
  );
}
