// ── Knowledge Source Registry — Source-of-Truth Architecture Layer ────────
// Central inventory of where Trail OS and Penny pull trusted information from.
// This is governance architecture — no live API connections yet.

export type SourceType =
  | 'Salesforce Knowledge'
  | 'Google Drive'
  | 'LMS Content'
  | 'Assessments'
  | 'Standards Studio'
  | 'Curriculum Studio'
  | 'Penny Generated'
  | 'Slack History'
  | 'Google Chat History'
  | 'Calendar Events';

export type TrustLevel =
  | 'Authoritative'
  | 'Trusted'
  | 'Curated'
  | 'Unverified';

export type SyncStatus =
  | 'Live'
  | 'Manual'
  | 'Disconnected'
  | 'Planned'
  | 'Future';

export type AccessStatus =
  | 'Open'
  | 'Restricted'
  | 'Pending'
  | 'Not Connected';

export type SourceAvailability =
  | 'Available'
  | 'Partial'
  | 'Planned'
  | 'Future';

export type HealthStatus =
  | 'Healthy'
  | 'Warning'
  | 'Critical'
  | 'Future';

export interface KnowledgeSource {
  id: string;
  name: string;
  shortName: string;
  type: SourceType;
  owner: string;
  systemOfRecord: string;
  description: string;
  purpose: string;
  relatedPrograms: string[];
  relatedKnowledgeCategories: string[];
  relatedSfObjects: string[];
  relatedPennyCapabilities: string[];       // capability ids from pennyCapabilityData
  relatedStandards: string[];               // standard ids
  relatedSources: string[];                 // other source ids
  trustLevel: TrustLevel;
  reviewCycle: string;
  lastReviewDate: string;
  nextReviewDate: string;
  accessStatus: AccessStatus;
  syncStatus: SyncStatus;
  availability: SourceAvailability;
  approvedForPenny: boolean;
  pennyUseDescription: string;
  healthStatus: HealthStatus;
  healthIssues: string[];
  futureIntegrationPath: string;
  integrationPriority: 'P1' | 'P2' | 'P3';
  sampleContents?: string[];
  sfCategory?: string;                      // for Salesforce Knowledge sources
}

export interface PennyRetrievalEntry {
  capabilityId: string;
  capabilityName: string;
  capabilityDomain: string;
  retrievalSteps: {
    order: number;
    sourceId: string;
    role: 'Primary' | 'Secondary' | 'Fallback' | 'Context';
    reasoning: string;
    confidenceImpact: 'High' | 'Medium' | 'Low';
  }[];
  retrievalNote: string;
}

export interface SourceHealthIssue {
  sourceId: string;
  issue: string;
  severity: 'Critical' | 'Warning' | 'Info';
  recommendation: string;
}

// ── Config ─────────────────────────────────────────────────────────────────

export const SOURCE_TYPE_CONFIG: Record<SourceType, { cls: string; description: string; icon: string }> = {
  'Salesforce Knowledge':  { cls: 'text-blue-700 bg-blue-50 border-blue-200',       description: 'Knowledge articles published in Salesforce Knowledge',                      icon: 'database' },
  'Google Drive':          { cls: 'text-green-700 bg-green-50 border-green-200',     description: 'Program folders, coach guides, and resources in Google Drive',              icon: 'folder-open' },
  'LMS Content':           { cls: 'text-amber-700 bg-amber-50 border-amber-200',     description: 'Module and lesson content delivered through the LMS platform',              icon: 'graduation-cap' },
  'Assessments':           { cls: 'text-violet-700 bg-violet-50 border-violet-200',  description: 'Assessment questions, results, and scoring data',                           icon: 'check-square' },
  'Standards Studio':      { cls: 'text-rose-700 bg-rose-50 border-rose-200',        description: 'Content quality rules and Penny prompt standards defined in Standards Studio', icon: 'shield-check' },
  'Curriculum Studio':     { cls: 'text-orange-700 bg-orange-50 border-orange-200',  description: 'Module outlines, lesson templates, and Penny curriculum assets',            icon: 'layers' },
  'Penny Generated':       { cls: 'text-secondary border-secondary/20 bg-secondary/10', description: 'Content and logs generated by Penny: coaching messages, reflections, summaries', icon: 'brain' },
  'Slack History':         { cls: 'text-slate-700 bg-slate-50 border-slate-200',     description: 'Future: Slack conversation history from coaching threads and cohort channels', icon: 'message-square' },
  'Google Chat History':   { cls: 'text-slate-700 bg-slate-50 border-slate-200',     description: 'Future: Google Chat conversation history from program spaces',              icon: 'message-circle' },
  'Calendar Events':       { cls: 'text-cyan-700 bg-cyan-50 border-cyan-200',        description: 'Future: Google Calendar event data for session context and sprint tracking', icon: 'calendar' },
};

export const TRUST_LEVEL_CONFIG: Record<TrustLevel, { cls: string; description: string; order: number }> = {
  'Authoritative': { cls: 'text-green-700 bg-green-50 border-green-200',    description: 'Single source of truth. Penny treats this as ground truth with no override.', order: 1 },
  'Trusted':       { cls: 'text-blue-700 bg-blue-50 border-blue-200',       description: 'Vetted and reviewed. Penny uses without additional validation.',              order: 2 },
  'Curated':       { cls: 'text-amber-700 bg-amber-50 border-amber-200',    description: 'Human-reviewed subset. Penny uses but flags as curated.',                    order: 3 },
  'Unverified':    { cls: 'text-rose-700 bg-rose-50 border-rose-200',       description: 'Not yet reviewed. Penny should not use without explicit approval.',          order: 4 },
};

export const SYNC_STATUS_CONFIG: Record<SyncStatus, { cls: string; label: string }> = {
  'Live':          { cls: 'text-green-700 bg-green-50 border-green-200',    label: 'Live Sync'      },
  'Manual':        { cls: 'text-amber-700 bg-amber-50 border-amber-200',    label: 'Manual Update'  },
  'Disconnected':  { cls: 'text-rose-700 bg-rose-50 border-rose-200',       label: 'Disconnected'   },
  'Planned':       { cls: 'text-violet-700 bg-violet-50 border-violet-200', label: 'Planned'        },
  'Future':        { cls: 'text-slate-500 bg-slate-50 border-slate-200',    label: 'Future'         },
};

export const HEALTH_CONFIG: Record<HealthStatus, { cls: string; dotCls: string }> = {
  'Healthy':  { cls: 'text-green-700 bg-green-50 border-green-200',    dotCls: 'bg-green-500'  },
  'Warning':  { cls: 'text-amber-700 bg-amber-50 border-amber-200',    dotCls: 'bg-amber-500'  },
  'Critical': { cls: 'text-rose-700 bg-rose-50 border-rose-200',       dotCls: 'bg-rose-500'   },
  'Future':   { cls: 'text-slate-500 bg-slate-50 border-slate-200',    dotCls: 'bg-slate-300'  },
};

// ── SF Knowledge Category Taxonomy ─────────────────────────────────────────

export const SF_KNOWLEDGE_CATEGORIES = [
  {
    id: 'mission-delivery',
    name: 'Mission & Delivery',
    description: 'Program models, organizational mission, coaching delivery standards, learner pathways, and program-specific content.',
    subcategories: ['Program Model', 'Coaching Delivery', 'Learner Pathways', 'Career Outcomes', 'Participant Guidelines'],
  },
  {
    id: 'operations-business',
    name: 'Operations & Business',
    description: 'Internal operational processes, business policies, staffing, finance, and partner management.',
    subcategories: ['Internal Operations', 'Business Policies', 'Partner Management', 'Staff Onboarding', 'Compliance'],
  },
  {
    id: 'technology-trail-os',
    name: 'Technology & Trail OS',
    description: 'Salesforce platform how-tos, Trail OS documentation, system configuration, and technical standards.',
    subcategories: ['Salesforce Platform', 'Trail OS', 'System Configuration', 'Integration Guides', 'Data Model'],
  },
];

// ── Knowledge Sources ───────────────────────────────────────────────────────

export const knowledgeSources: KnowledgeSource[] = [

  // ── Salesforce Knowledge ───────────────────────────────────────────────

  {
    id: 'src-sf-mission-delivery',
    name: 'Salesforce Knowledge — Mission & Delivery',
    shortName: 'SF Knowledge: Mission',
    type: 'Salesforce Knowledge',
    sfCategory: 'Mission & Delivery',
    owner: 'Knowledge Lead',
    systemOfRecord: 'Salesforce',
    description: 'Knowledge articles covering program model, coaching delivery approach, learner pathways, career outcomes, and participant guidelines.',
    purpose: 'Authoritative reference for how Transition Trails delivers its programs. Penny uses this to answer coaching questions, provide career guidance, and stay aligned with organizational standards.',
    relatedPrograms: ['Foundations Trail', 'Guided Trail', "Explorer's Trail", 'All programs'],
    relatedKnowledgeCategories: ['Mission & Delivery', 'Coaching', 'Career'],
    relatedSfObjects: ['Knowledge__c', 'Program_Engagement__c', 'Contact'],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-resume-review', 'cap-knowledge-retrieval'],
    relatedStandards: ['std-knowledge-article', 'std-coach-notes'],
    relatedSources: ['src-sf-ops-business', 'src-curriculum-studio', 'src-standards-studio'],
    trustLevel: 'Authoritative',
    reviewCycle: 'Quarterly',
    lastReviewDate: 'March 2025',
    nextReviewDate: 'June 2025',
    accessStatus: 'Open',
    syncStatus: 'Manual',
    availability: 'Available',
    approvedForPenny: true,
    pennyUseDescription: 'Primary knowledge source for coaching conversations, career guidance, and answering learner questions about the program model and pathway. Penny retrieves directly and cites.',
    healthStatus: 'Warning',
    healthIssues: ['Review date approaching June 2025 — schedule quarterly review', 'Sync is manual — no live connection to Salesforce Knowledge API yet'],
    futureIntegrationPath: 'Q3 2025 — Salesforce Knowledge API. Live sync with 24h refresh cadence. Penny RAG pipeline ingests on update.',
    integrationPriority: 'P1',
    sampleContents: ['Foundations Trail Program Model Overview', 'Coaching Delivery Standards', 'Learner Pathway: Admin to Analyst', 'Career Outcomes Framework'],
  },

  {
    id: 'src-sf-ops-business',
    name: 'Salesforce Knowledge — Operations & Business',
    shortName: 'SF Knowledge: Operations',
    type: 'Salesforce Knowledge',
    sfCategory: 'Operations & Business',
    owner: 'Operations Lead',
    systemOfRecord: 'Salesforce',
    description: 'Knowledge articles covering internal operations, business policies, partner management, staff onboarding, and compliance.',
    purpose: 'Internal operational reference. Penny uses this selectively for coach-facing interactions that require policy context — not exposed to learners directly.',
    relatedPrograms: ['Internal'],
    relatedKnowledgeCategories: ['Operations', 'Business'],
    relatedSfObjects: ['Knowledge__c'],
    relatedPennyCapabilities: ['cap-escalations', 'cap-executive-briefs'],
    relatedStandards: [],
    relatedSources: ['src-sf-mission-delivery', 'src-sf-technology'],
    trustLevel: 'Trusted',
    reviewCycle: 'Bi-annually',
    lastReviewDate: 'January 2025',
    nextReviewDate: 'July 2025',
    accessStatus: 'Restricted',
    syncStatus: 'Manual',
    availability: 'Available',
    approvedForPenny: false,
    pennyUseDescription: 'Not currently approved for direct Penny retrieval. Used by executive briefs and escalation summaries with human review required.',
    healthStatus: 'Warning',
    healthIssues: ['Not yet approved for Penny retrieval — requires compliance review', 'Some articles >12 months without update — flag for review'],
    futureIntegrationPath: 'Q4 2025 — Restricted Penny access. Coach-only context injection. No learner-facing retrieval.',
    integrationPriority: 'P2',
    sampleContents: ['Internal Operations Handbook', 'Partner Management Policies', 'Staff Onboarding Guide'],
  },

  {
    id: 'src-sf-technology',
    name: 'Salesforce Knowledge — Technology & Trail OS',
    shortName: 'SF Knowledge: Technology',
    type: 'Salesforce Knowledge',
    sfCategory: 'Technology & Trail OS',
    owner: 'Technology Lead',
    systemOfRecord: 'Salesforce',
    description: 'Knowledge articles covering Salesforce platform how-tos, Trail OS documentation, system configuration guides, and technical standards for the Transition Trails implementation.',
    purpose: 'Technical reference for the team and for Penny when answering learner questions about Salesforce concepts, Trail OS navigation, and system behavior.',
    relatedPrograms: ['Foundations Trail', "Explorer's Trail", 'Internal'],
    relatedKnowledgeCategories: ['Technology', 'Trail OS', 'Salesforce Platform'],
    relatedSfObjects: ['Knowledge__c'],
    relatedPennyCapabilities: ['cap-knowledge-retrieval', 'cap-study-coach'],
    relatedStandards: ['std-knowledge-article'],
    relatedSources: ['src-sf-mission-delivery', 'src-curriculum-studio'],
    trustLevel: 'Authoritative',
    reviewCycle: 'Monthly (tech changes frequently)',
    lastReviewDate: 'May 2025',
    nextReviewDate: 'June 2025',
    accessStatus: 'Open',
    syncStatus: 'Manual',
    availability: 'Available',
    approvedForPenny: true,
    pennyUseDescription: 'Penny uses this to answer learner Salesforce and Trail OS questions. Highest accuracy requirement — incorrect technical guidance is a trust risk.',
    healthStatus: 'Healthy',
    healthIssues: [],
    futureIntegrationPath: 'Q3 2025 — Live SF Knowledge API sync. Highest priority for RAG pipeline accuracy.',
    integrationPriority: 'P1',
    sampleContents: ['Salesforce Admin: Object Model Reference', 'Trail OS Navigation Guide', 'Custom Object Setup How-To', 'Apex vs Flow Decision Guide'],
  },

  // ── Google Drive ────────────────────────────────────────────────────────

  {
    id: 'src-gdrive-foundations',
    name: 'Foundations Trail Google Drive Folder',
    shortName: 'GDrive: Foundations Trail',
    type: 'Google Drive',
    owner: 'Curriculum Lead',
    systemOfRecord: 'Google Drive',
    description: 'Google Drive folder containing all Foundations Trail program materials: coach guides, sprint schedules, assessment rubrics, reference documents, and session resources.',
    purpose: 'Source of truth for all Foundations Trail program assets not yet in the LMS or Salesforce. Penny uses this for program context, coach guidance, and supplementary content.',
    relatedPrograms: ['Foundations Trail'],
    relatedKnowledgeCategories: ['Mission & Delivery', 'Coaching', 'Curriculum'],
    relatedSfObjects: ['Program__c', 'Training_Plan__c'],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-study-coach', 'cap-trail-quests'],
    relatedStandards: ['std-module', 'std-lesson', 'std-coach-notes'],
    relatedSources: ['src-lms-modules', 'src-curriculum-studio', 'src-sf-mission-delivery'],
    trustLevel: 'Trusted',
    reviewCycle: 'Per sprint',
    lastReviewDate: 'May 2025',
    nextReviewDate: 'June 2025',
    accessStatus: 'Restricted',
    syncStatus: 'Manual',
    availability: 'Partial',
    approvedForPenny: false,
    pennyUseDescription: 'Drive API is connected. Penny access pending folder indexing configuration and content trust review.',
    healthStatus: 'Warning',
    healthIssues: ['Folder indexing not yet configured — content not accessible to Trail OS', 'Not approved for Penny until folder sync is set up and content reviewed', 'Folder structure not yet mapped to curriculum module schema'],
    futureIntegrationPath: 'Folder indexing → RAG pipeline. Content must pass Standards Studio review before Penny access.',
    integrationPriority: 'P1',
    sampleContents: ['Sprint 1 Coach Guide', 'Module Assessment Rubrics', 'Learner Reference Packet', 'Office Hours Agenda Templates'],
  },

  {
    id: 'src-gdrive-guided',
    name: 'Guided Trail Google Drive Folder',
    shortName: 'GDrive: Guided Trail',
    type: 'Google Drive',
    owner: 'Curriculum Lead',
    systemOfRecord: 'Google Drive',
    description: 'Google Drive folder containing all Guided Trail program materials, coach resources, sprint documentation, and supplementary learning assets.',
    purpose: 'Source of truth for Guided Trail assets. Penny context layer for the Guided Trail program experience.',
    relatedPrograms: ['Guided Trail'],
    relatedKnowledgeCategories: ['Mission & Delivery', 'Curriculum'],
    relatedSfObjects: ['Program__c'],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-reflection-prompts'],
    relatedStandards: ['std-module', 'std-coach-notes'],
    relatedSources: ['src-gdrive-foundations', 'src-curriculum-studio'],
    trustLevel: 'Trusted',
    reviewCycle: 'Per sprint',
    lastReviewDate: 'April 2025',
    nextReviewDate: 'June 2025',
    accessStatus: 'Restricted',
    syncStatus: 'Manual',
    availability: 'Partial',
    approvedForPenny: false,
    pennyUseDescription: 'Drive API is connected. Folder indexing and content review pending — mirrors Foundations Trail Drive setup.',
    healthStatus: 'Warning',
    healthIssues: ['Folder indexing not yet configured — content not accessible to Trail OS', 'Folder content not yet indexed for Penny retrieval'],
    futureIntegrationPath: 'Same indexing pipeline as Foundations Trail Drive. Configure after Foundations folder is set up.',
    integrationPriority: 'P2',
    sampleContents: ['Sprint Schedule', 'Cohort Kick-off Materials', 'Module Resource Packs'],
  },

  {
    id: 'src-gdrive-source-docs',
    name: 'Source Document Archive',
    shortName: 'Source Doc Archive',
    type: 'Google Drive',
    owner: 'Knowledge Lead',
    systemOfRecord: 'Google Drive',
    description: 'Curated archive of reference documents, research papers, Salesforce documentation, and source materials uploaded to Trail OS and mapped via Source Mapping.',
    purpose: 'Supplementary reference layer. Penny uses these for answering nuanced questions that require external Salesforce documentation or research-backed content.',
    relatedPrograms: ['All programs'],
    relatedKnowledgeCategories: ['Technology', 'Mission & Delivery'],
    relatedSfObjects: ['Knowledge__c'],
    relatedPennyCapabilities: ['cap-knowledge-retrieval', 'cap-source-recommendations'],
    relatedStandards: ['std-knowledge-article'],
    relatedSources: ['src-sf-technology', 'src-sf-mission-delivery'],
    trustLevel: 'Curated',
    reviewCycle: 'As uploaded',
    lastReviewDate: 'May 2025',
    nextReviewDate: 'August 2025',
    accessStatus: 'Open',
    syncStatus: 'Manual',
    availability: 'Available',
    approvedForPenny: true,
    pennyUseDescription: 'Secondary retrieval source. Penny uses when primary SF Knowledge sources do not answer a query. Always cites source document and upload date.',
    healthStatus: 'Warning',
    healthIssues: ['12 documents awaiting category mapping', '3 documents have no owner assigned', 'No automated review trigger — items can become stale'],
    futureIntegrationPath: 'Q3 2025 — Automated indexing on upload. Standards Studio compliance check before Penny ingestion.',
    integrationPriority: 'P2',
    sampleContents: ['Salesforce Certified Admin Study Guide', 'Nonprofit Cloud Reference', 'Trailhead Module Index Export'],
  },

  // ── LMS Content ─────────────────────────────────────────────────────────

  {
    id: 'src-lms-modules',
    name: 'LMS Course Modules',
    shortName: 'LMS Modules',
    type: 'LMS Content',
    owner: 'Curriculum Lead',
    systemOfRecord: 'LMS Platform',
    description: 'All published course module content, lesson text, activities, and embedded resources delivered through the LMS platform across all active programs.',
    purpose: 'Core learning content that Penny uses as context for coaching, answering module questions, guiding study, and generating reflections. The most frequently accessed source during active program delivery.',
    relatedPrograms: ['Foundations Trail', 'Guided Trail', "Explorer's Trail"],
    relatedKnowledgeCategories: ['Curriculum', 'Mission & Delivery'],
    relatedSfObjects: ['Training_Plan__c', 'Training_Plan_Item__c'],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-study-coach', 'cap-reflection-prompts', 'cap-trail-quests', 'cap-progress-insights'],
    relatedStandards: ['std-module', 'std-lesson', 'std-reflection-prompt'],
    relatedSources: ['src-curriculum-studio', 'src-assessments', 'src-gdrive-foundations'],
    trustLevel: 'Authoritative',
    reviewCycle: 'Per cohort',
    lastReviewDate: 'May 2025',
    nextReviewDate: 'July 2025',
    accessStatus: 'Open',
    syncStatus: 'Manual',
    availability: 'Available',
    approvedForPenny: true,
    pennyUseDescription: 'Highest priority source for active program coaching. Penny retrieves current module content before every learner interaction to ensure context accuracy. Must stay synchronized with published LMS state.',
    healthStatus: 'Warning',
    healthIssues: ['LMS API not yet connected — sync is manual export', 'No completion event webhook — Penny cannot auto-trigger on module completion yet', 'Salesforce Training_Plan_Item__c relationship partially mapped'],
    futureIntegrationPath: 'Q3 2025 — LMS webhook for completion events. Module content API sync. Primary Penny context injection source.',
    integrationPriority: 'P1',
    sampleContents: ['Module 1: Salesforce Fundamentals', 'Module 2: Object Model Deep Dive', 'Module 3: Automation Tools', 'Module 4: Reports & Dashboards'],
  },

  // ── Assessments ──────────────────────────────────────────────────────────

  {
    id: 'src-assessments',
    name: 'Salesforce Assessment Objects',
    shortName: 'SF Assessments',
    type: 'Assessments',
    owner: 'Curriculum Lead',
    systemOfRecord: 'Salesforce',
    description: 'Assessment questions, learner response data, scoring results, and pass/fail records stored as Salesforce objects. The system of record for all learner assessment history.',
    purpose: 'Penny reads assessment data to understand where a learner is struggling, trigger coaching interventions, identify escalation signals, and personalize study guidance.',
    relatedPrograms: ['Foundations Trail', 'Guided Trail'],
    relatedKnowledgeCategories: ['Assessments', 'Learner Progress'],
    relatedSfObjects: ['Training_Plan_Item__c', 'Program_Engagement__c'],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-escalations', 'cap-study-coach', 'cap-cohort-summaries', 'cap-progress-insights'],
    relatedStandards: [],
    relatedSources: ['src-lms-modules', 'src-sf-mission-delivery'],
    trustLevel: 'Authoritative',
    reviewCycle: 'Continuous (assessment records are live data)',
    lastReviewDate: 'May 2025',
    nextReviewDate: 'Ongoing',
    accessStatus: 'Restricted',
    syncStatus: 'Manual',
    availability: 'Available',
    approvedForPenny: true,
    pennyUseDescription: 'Penny reads assessment scores and pass/fail patterns to personalize coaching messages, trigger escalation, and generate progress insights. Restricted — never exposed verbatim to learners, only interpreted.',
    healthStatus: 'Warning',
    healthIssues: ['No live Salesforce API connection — data pulled manually for prototype', 'Assessment → module mapping is incomplete for Sprint 3+', 'Category mapping missing for 40% of assessment items'],
    futureIntegrationPath: 'Q3 2025 — Live Salesforce SOQL queries. Penny reads in real-time per coaching interaction.',
    integrationPriority: 'P1',
    sampleContents: ['Declarative Automation Assessment', 'Data Model Quiz', 'Reports & Dashboards Evaluation', 'Certification Readiness Check'],
  },

  // ── Standards Studio ─────────────────────────────────────────────────────

  {
    id: 'src-standards-studio',
    name: 'Standards Studio Rules',
    shortName: 'Standards Studio',
    type: 'Standards Studio',
    owner: 'Curriculum Lead',
    systemOfRecord: 'Trail OS — Standards Studio',
    description: 'Content quality rules and Penny prompt standards defined in Standards Studio. Governs what valid modules, lessons, knowledge articles, reflections, coaching messages, and Penny outputs look like.',
    purpose: 'Penny\'s rule layer. Before generating or delivering any content, Penny checks the applicable standard to ensure quality, tone, structure, and required fields are met. This is how content quality is enforced at scale.',
    relatedPrograms: ['All programs'],
    relatedKnowledgeCategories: ['Standards', 'Quality'],
    relatedSfObjects: [],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-reflection-prompts', 'cap-trail-quests', 'cap-knowledge-retrieval'],
    relatedStandards: ['std-module', 'std-lesson', 'std-knowledge-article', 'std-penny-prompt', 'std-reflection-prompt', 'std-coach-notes'],
    relatedSources: ['src-curriculum-studio', 'src-sf-mission-delivery'],
    trustLevel: 'Authoritative',
    reviewCycle: 'Quarterly (or when standards are updated)',
    lastReviewDate: 'May 2025',
    nextReviewDate: 'August 2025',
    accessStatus: 'Open',
    syncStatus: 'Live',
    availability: 'Available',
    approvedForPenny: true,
    pennyUseDescription: 'Penny reads Standards Studio rules before every content generation step. Acts as the quality gate — content that fails a standard check is flagged, not delivered. This is the highest-trust rule source.',
    healthStatus: 'Healthy',
    healthIssues: [],
    futureIntegrationPath: 'Live — Standards Studio is a Trail OS-native source. No external sync needed. Standards updates are immediately available to Penny.',
    integrationPriority: 'P1',
    sampleContents: ['Module Standard (10 rules)', 'Lesson Standard (8 rules)', 'Reflection Prompt Standard (6 rules)', 'Penny Prompt Standard (7 rules)', 'Coach Notes Standard (5 rules)'],
  },

  // ── Curriculum Studio ────────────────────────────────────────────────────

  {
    id: 'src-curriculum-studio',
    name: 'Curriculum Studio Content',
    shortName: 'Curriculum Studio',
    type: 'Curriculum Studio',
    owner: 'Curriculum Lead',
    systemOfRecord: 'Trail OS — Curriculum Studio',
    description: 'Module outlines, lesson frameworks, Penny asset definitions, delivery asset specifications, and curriculum metadata authored in Trail OS Curriculum Studio.',
    purpose: 'The structural design standard for all learning content. Penny uses curriculum data to understand the intended module sequence, learning objectives, and delivery design — so coaching and questing stay aligned with the curriculum.',
    relatedPrograms: ['Foundations Trail', 'Guided Trail', "Explorer's Trail"],
    relatedKnowledgeCategories: ['Curriculum', 'Program Design'],
    relatedSfObjects: ['Training_Plan__c', 'Training_Plan_Item__c'],
    relatedPennyCapabilities: ['cap-study-coach', 'cap-trail-quests', 'cap-reflection-prompts', 'cap-cohort-summaries'],
    relatedStandards: ['std-module', 'std-lesson'],
    relatedSources: ['src-standards-studio', 'src-lms-modules', 'src-gdrive-foundations'],
    trustLevel: 'Authoritative',
    reviewCycle: 'Per sprint',
    lastReviewDate: 'May 2025',
    nextReviewDate: 'June 2025',
    accessStatus: 'Open',
    syncStatus: 'Live',
    availability: 'Available',
    approvedForPenny: true,
    pennyUseDescription: 'Penny reads curriculum structure before generating module-specific content. This is the scaffold — Penny knows module sequence, learning objectives, and what assets exist for each module.',
    healthStatus: 'Healthy',
    healthIssues: [],
    futureIntegrationPath: 'Live — Curriculum Studio is Trail OS-native. Structural data is immediately available. Future: LMS export pipeline wires this to live delivery data.',
    integrationPriority: 'P1',
    sampleContents: ['Module Outline: Sprint 1-4', 'Lesson Templates per Module', 'Penny Asset Definitions', 'Delivery Asset Map'],
  },

  // ── Penny Generated ──────────────────────────────────────────────────────

  {
    id: 'src-penny-generated',
    name: 'Penny Content Assistant Outputs',
    shortName: 'Penny Outputs',
    type: 'Penny Generated',
    owner: 'Penny Product Lead',
    systemOfRecord: 'Trail OS — Penny Command Center',
    description: 'Coaching messages, reflection prompts, weekly summaries, cohort briefs, and other content generated by Penny and reviewed through the Content Assistant workflow.',
    purpose: 'Creates a feedback loop. Penny\'s reviewed and approved outputs become training examples and prompt templates for future Penny interactions. Enables quality improvement over time.',
    relatedPrograms: ['All programs'],
    relatedKnowledgeCategories: ['Penny', 'Coaching', 'Curriculum'],
    relatedSfObjects: ['Program_Engagement__c'],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-reflection-prompts', 'cap-cohort-summaries'],
    relatedStandards: ['std-penny-prompt', 'std-reflection-prompt'],
    relatedSources: ['src-standards-studio', 'src-curriculum-studio'],
    trustLevel: 'Curated',
    reviewCycle: 'Per output (human review required before re-use)',
    lastReviewDate: 'May 2025',
    nextReviewDate: 'Ongoing',
    accessStatus: 'Restricted',
    syncStatus: 'Manual',
    availability: 'Partial',
    approvedForPenny: false,
    pennyUseDescription: 'Not yet approved for automatic Penny retrieval. Human-reviewed outputs can be promoted to prompt templates manually. Automation planned Q4 2025.',
    healthStatus: 'Warning',
    healthIssues: ['No automated feedback loop yet — outputs are logged but not re-ingested', 'Approval workflow for output promotion to templates is manual', 'Not approved for automated Penny use without human review'],
    futureIntegrationPath: 'Q4 2025 — Automated quality scoring. Approved outputs promoted to template library. Penny learns from highest-rated coaching messages.',
    integrationPriority: 'P2',
    sampleContents: ['Sprint 1 Reflection Prompts (reviewed set)', 'Weekly Coaching Message Templates', 'Cohort Summary Drafts'],
  },

  {
    id: 'src-coach-notes',
    name: 'Coach Notes Library',
    shortName: 'Coach Notes',
    type: 'Salesforce Knowledge',
    sfCategory: 'Mission & Delivery',
    owner: 'Coach Team Lead',
    systemOfRecord: 'Salesforce',
    description: 'Coach-authored notes on learner cohorts, escalation patterns, and program delivery insights. Stored in Salesforce and governed by the Coach Notes standard.',
    purpose: 'Penny reads coach notes to understand escalation triggers, learner struggle patterns, and context that helps Penny calibrate coaching tone and urgency per cohort.',
    relatedPrograms: ['Foundations Trail', 'Guided Trail'],
    relatedKnowledgeCategories: ['Coaching', 'Mission & Delivery'],
    relatedSfObjects: ['Knowledge__c', 'Program_Engagement__c'],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-escalations', 'cap-cohort-summaries'],
    relatedStandards: ['std-coach-notes'],
    relatedSources: ['src-sf-mission-delivery', 'src-assessments'],
    trustLevel: 'Trusted',
    reviewCycle: 'Per cohort',
    lastReviewDate: 'April 2025',
    nextReviewDate: 'June 2025',
    accessStatus: 'Restricted',
    syncStatus: 'Manual',
    availability: 'Available',
    approvedForPenny: true,
    pennyUseDescription: 'Penny reads coach notes in strict read-only mode for escalation context. Never surfaces raw coach notes to learners. Used to calibrate coaching urgency and escalation messaging.',
    healthStatus: 'Warning',
    healthIssues: ['Adherence to Coach Notes standard is 60% — 4 of 10 recent notes missing required sections', 'No live Salesforce API yet — manual sync only'],
    futureIntegrationPath: 'Q3 2025 — Live Salesforce API. Read-only Penny access. Standards Studio compliance check on write.',
    integrationPriority: 'P2',
    sampleContents: ['Sprint 2 Cohort Notes: Escalation Patterns', 'Module 3 Common Misconceptions', 'High-Engagement Learner Characteristics'],
  },

  // ── Future Sources ────────────────────────────────────────────────────────

  {
    id: 'src-future-slack',
    name: 'Future: Slack Conversation History',
    shortName: 'Slack History',
    type: 'Slack History',
    owner: 'Communications Lead',
    systemOfRecord: 'Slack',
    description: 'Future source: Slack conversation history from coaching DM threads and cohort channels, once Penny Slack integration is live.',
    purpose: 'When connected, Slack history will allow Penny to reference prior conversations in context — understanding what questions a learner has already asked, what was resolved, and what follows up.',
    relatedPrograms: ['Foundations Trail', 'Guided Trail'],
    relatedKnowledgeCategories: ['Communications', 'Coaching'],
    relatedSfObjects: ['Program_Engagement__c'],
    relatedPennyCapabilities: ['cap-learner-coaching', 'cap-slack-messaging', 'cap-weekly-reviews'],
    relatedStandards: ['std-slack-activity'],
    relatedSources: ['src-penny-generated', 'src-assessments'],
    trustLevel: 'Unverified',
    reviewCycle: 'Continuous (real-time)',
    lastReviewDate: 'Not yet',
    nextReviewDate: 'Q3 2025',
    accessStatus: 'Not Connected',
    syncStatus: 'Future',
    availability: 'Future',
    approvedForPenny: false,
    pennyUseDescription: 'Not yet available. When connected, Penny will use recent DM history as conversation context (last 5 turns) and channel history for cohort-level pattern detection.',
    healthStatus: 'Future',
    healthIssues: ['Source does not exist yet — pending Slack API integration', 'Privacy and data retention policy not yet defined', 'Learner consent model for conversation logging not designed'],
    futureIntegrationPath: 'Q3 2025 — Slack Bolt app. Conversation logging with learner consent. Retention: 90-day rolling window.',
    integrationPriority: 'P2',
  },

  {
    id: 'src-future-calendar',
    name: 'Future: Google Calendar Events',
    shortName: 'Calendar Events',
    type: 'Calendar Events',
    owner: 'Communications Lead',
    systemOfRecord: 'Google Calendar',
    description: 'Future source: Google Calendar event data for program sessions, sprint deadlines, office hours, and assessment windows.',
    purpose: 'When connected, Calendar data will allow Penny to send context-aware reminders and tie coaching messages to upcoming sessions — "you have office hours tomorrow, here\'s what to bring."',
    relatedPrograms: ['All programs'],
    relatedKnowledgeCategories: ['Communications', 'Program Schedule'],
    relatedSfObjects: ['Service_Schedule__c', 'Service_Attendance__c'],
    relatedPennyCapabilities: ['cap-calendar-reminders', 'cap-weekly-reviews'],
    relatedStandards: ['std-calendar-reminder'],
    relatedSources: ['src-sf-mission-delivery'],
    trustLevel: 'Unverified',
    reviewCycle: 'Continuous (real-time)',
    lastReviewDate: 'Not yet',
    nextReviewDate: 'Q3 2025',
    accessStatus: 'Not Connected',
    syncStatus: 'Future',
    availability: 'Future',
    approvedForPenny: false,
    pennyUseDescription: 'Not yet available. When connected, Calendar events will be the trigger source for reminder capabilities and the scheduling context for weekly review conversations.',
    healthStatus: 'Future',
    healthIssues: ['Source does not exist yet — pending Google Calendar API integration', 'Calendar schema mapping to Salesforce Service_Schedule__c not yet designed'],
    futureIntegrationPath: 'Q3 2025 — Google Calendar API via service account. Read-only event access. Penny triggers on event proximity (24h, 1h, 15min).',
    integrationPriority: 'P2',
  },
];

// ── Penny Retrieval Map ──────────────────────────────────────────────────────

export const pennyRetrievalMap: PennyRetrievalEntry[] = [
  {
    capabilityId: 'cap-learner-coaching',
    capabilityName: 'Learner Coaching',
    capabilityDomain: 'Coaching',
    retrievalNote: 'Every coaching interaction loads a context envelope: current module (LMS), learner progress (Assessments), and coaching rules (Standards Studio). Coach notes are loaded if an escalation flag is active.',
    retrievalSteps: [
      { order: 1, sourceId: 'src-lms-modules',          role: 'Primary',   reasoning: 'Current module content gives Penny the topic being studied. Cannot coach accurately without this.', confidenceImpact: 'High' },
      { order: 2, sourceId: 'src-assessments',          role: 'Primary',   reasoning: 'Assessment scores reveal where the learner is struggling. Penny personalizes based on performance patterns.', confidenceImpact: 'High' },
      { order: 3, sourceId: 'src-standards-studio',     role: 'Context',   reasoning: 'Coach Notes standard defines what valid coaching looks like — tone, escalation triggers, format.', confidenceImpact: 'Medium' },
      { order: 4, sourceId: 'src-sf-mission-delivery',  role: 'Secondary', reasoning: 'Program model context — Penny stays aligned to the organization\'s coaching delivery approach.', confidenceImpact: 'Medium' },
      { order: 5, sourceId: 'src-coach-notes',          role: 'Fallback',  reasoning: 'Read only when escalation signals are detected. Gives Penny human-coach context.', confidenceImpact: 'High' },
    ],
  },
  {
    capabilityId: 'cap-knowledge-retrieval',
    capabilityName: 'Knowledge Retrieval',
    capabilityDomain: 'Knowledge',
    retrievalNote: 'Penny searches in priority order. If SF Knowledge answers the question with high confidence, retrieval stops. Source documents are the fallback for edge cases.',
    retrievalSteps: [
      { order: 1, sourceId: 'src-sf-technology',        role: 'Primary',   reasoning: 'Technology questions are the most common learner query. Highest accuracy requirement.', confidenceImpact: 'High' },
      { order: 2, sourceId: 'src-sf-mission-delivery',  role: 'Primary',   reasoning: 'Program and career questions are second most common. Authoritative for coaching alignment.', confidenceImpact: 'High' },
      { order: 3, sourceId: 'src-curriculum-studio',    role: 'Secondary', reasoning: 'For questions about the program structure — what\'s in a module, what\'s coming next.', confidenceImpact: 'Medium' },
      { order: 4, sourceId: 'src-gdrive-source-docs',   role: 'Fallback',  reasoning: 'Supplementary for edge-case technical questions not in SF Knowledge.', confidenceImpact: 'Low' },
      { order: 5, sourceId: 'src-standards-studio',     role: 'Context',   reasoning: 'Penny checks that its answer format meets the Knowledge Article standard before delivering.', confidenceImpact: 'Medium' },
    ],
  },
  {
    capabilityId: 'cap-resume-review',
    capabilityName: 'Resume Review',
    capabilityDomain: 'Career',
    retrievalNote: 'Resume Review is career-domain context heavy. Penny loads role definitions, program progress, and certification data before generating feedback.',
    retrievalSteps: [
      { order: 1, sourceId: 'src-sf-mission-delivery',  role: 'Primary',   reasoning: 'Career outcomes framework defines what "Salesforce-ready" means for each role type.', confidenceImpact: 'High' },
      { order: 2, sourceId: 'src-assessments',          role: 'Primary',   reasoning: 'Certification progress and assessment scores tell Penny what skills the learner can credibly claim.', confidenceImpact: 'High' },
      { order: 3, sourceId: 'src-lms-modules',          role: 'Secondary', reasoning: 'Module completion tells Penny what topics the learner has covered — feeds "skills you can talk to" list.', confidenceImpact: 'Medium' },
      { order: 4, sourceId: 'src-gdrive-foundations',   role: 'Fallback',  reasoning: 'Program-specific career prep materials if available in Drive.', confidenceImpact: 'Low' },
    ],
  },
  {
    capabilityId: 'cap-reflection-prompts',
    capabilityName: 'Reflection Prompts',
    capabilityDomain: 'Coaching',
    retrievalNote: 'Reflection delivery is standards-driven. Penny loads the correct prompt from Curriculum Studio, validates against the Reflection Prompt standard, then delivers.',
    retrievalSteps: [
      { order: 1, sourceId: 'src-curriculum-studio',    role: 'Primary',   reasoning: 'Reflection prompts are authored in Curriculum Studio as Penny assets per module. This is the source.', confidenceImpact: 'High' },
      { order: 2, sourceId: 'src-standards-studio',     role: 'Context',   reasoning: 'Reflection Prompt standard validates the prompt has deepening question, follow-up logic, and format.', confidenceImpact: 'High' },
      { order: 3, sourceId: 'src-lms-modules',          role: 'Secondary', reasoning: 'Module context ensures the reflection is aligned to what the learner actually just completed.', confidenceImpact: 'Medium' },
    ],
  },
  {
    capabilityId: 'cap-study-coach',
    capabilityName: 'Study Coach',
    capabilityDomain: 'Learning',
    retrievalNote: 'Study coaching is pacing + content aware. Penny needs sprint schedule, current module content, and assessment history to generate an accurate study plan.',
    retrievalSteps: [
      { order: 1, sourceId: 'src-lms-modules',          role: 'Primary',   reasoning: 'Module content and sequence tells Penny what to study and in what order.', confidenceImpact: 'High' },
      { order: 2, sourceId: 'src-assessments',          role: 'Primary',   reasoning: 'Past performance identifies weak areas that need extra study time.', confidenceImpact: 'High' },
      { order: 3, sourceId: 'src-curriculum-studio',    role: 'Context',   reasoning: 'Sprint schedule and learning objectives structure the study plan scaffold.', confidenceImpact: 'Medium' },
      { order: 4, sourceId: 'src-sf-technology',        role: 'Fallback',  reasoning: 'For recommending supplementary Salesforce resources on specific topics.', confidenceImpact: 'Low' },
    ],
  },
];

// ── Summary ───────────────────────────────────────────────────────────────────

export const SOURCE_SUMMARY = {
  total:       knowledgeSources.length,
  available:   knowledgeSources.filter(s => s.availability === 'Available').length,
  partial:     knowledgeSources.filter(s => s.availability === 'Partial').length,
  future:      knowledgeSources.filter(s => s.availability === 'Future').length,
  approvedForPenny: knowledgeSources.filter(s => s.approvedForPenny).length,
  healthy:     knowledgeSources.filter(s => s.healthStatus === 'Healthy').length,
  warnings:    knowledgeSources.filter(s => s.healthStatus === 'Warning').length,
  critical:    knowledgeSources.filter(s => s.healthStatus === 'Critical').length,
  byType:      Object.fromEntries(
    (['Salesforce Knowledge','Google Drive','LMS Content','Assessments','Standards Studio','Curriculum Studio','Penny Generated','Slack History','Google Chat History','Calendar Events'] as SourceType[]).map(t => [
      t, knowledgeSources.filter(s => s.type === t).length,
    ])
  ) as Record<SourceType, number>,
};

export const SOURCE_TYPE_ORDER: SourceType[] = [
  'Salesforce Knowledge', 'Google Drive', 'LMS Content', 'Assessments',
  'Standards Studio', 'Curriculum Studio', 'Penny Generated',
  'Slack History', 'Google Chat History', 'Calendar Events',
];
