// ── Knowledge Source Registry — Source-of-Truth Architecture Layer ────────
// Central inventory of where Trail OS and Penny pull trusted information from.
// Runtime data comes from GET /api/knowledge/sources — see useKnowledgeSources().

export type SourceType =
  | 'Salesforce Knowledge'
  | 'Google Drive'
  | 'LMS Content'
  | 'Assessments'
  | 'Standards Studio'
  | 'Curriculum Studio'
  | 'Penny Generated'
  | 'Slack History'
  | 'Google Chat History'
  | 'Calendar Events';

export type TrustLevel =
  | 'Authoritative'
  | 'Trusted'
  | 'Curated'
  | 'Unverified';

export type SyncStatus =
  | 'Live'
  | 'Manual'
  | 'Disconnected'
  | 'Planned'
  | 'Future';

export type AccessStatus =
  | 'Open'
  | 'Restricted'
  | 'Pending'
  | 'Not Connected';

export type SourceAvailability =
  | 'Available'
  | 'Partial'
  | 'Planned'
  | 'Future';

export type HealthStatus =
  | 'Healthy'
  | 'Warning'
  | 'Critical'
  | 'Future';

export interface SourceDocument {
  id: string;
  name: string;
  categories: string[];
  uploadedBy?: string;
  uploadDate?: string;
  owner?: string;
}

export interface KnowledgeSource {
  id: string;
  name: string;
  shortName: string;
  type: SourceType;
  owner: string;
  systemOfRecord: string;
  description: string;
  purpose: string;
  relatedPrograms: string[];
  relatedKnowledgeCategories: string[];
  relatedSfObjects: string[];
  relatedPennyCapabilities: string[];
  relatedStandards: string[];
  relatedSources: string[];
  trustLevel: TrustLevel;
  reviewCycle: string;
  lastReviewDate: string;
  nextReviewDate: string;
  accessStatus: AccessStatus;
  syncStatus: SyncStatus;
  availability: SourceAvailability;
  approvedForPenny: boolean;
  pennyUseDescription: string;
  healthStatus: HealthStatus;
  healthIssues: string[];
  futureIntegrationPath: string;
  integrationPriority: 'P1' | 'P2' | 'P3';
  sampleContents?: string[];
  sfCategory?: string;
  documents?: SourceDocument[];
  // Live-enrichment fields injected at serve-time
  liveFileCount?: number | null;
  liveSfArticleCount?: number | null;
}

export interface PennyRetrievalEntry {
  capabilityId: string;
  capabilityName: string;
  capabilityDomain: string;
  retrievalSteps: {
    order: number;
    sourceId: string;
    role: 'Primary' | 'Secondary' | 'Fallback' | 'Context';
    reasoning: string;
    confidenceImpact: 'High' | 'Medium' | 'Low';
  }[];
  retrievalNote: string;
}

export interface SourceHealthIssue {
  sourceId: string;
  issue: string;
  severity: 'Critical' | 'Warning' | 'Info';
  recommendation: string;
}

// ── Config ─────────────────────────────────────────────────────────────────

export const SOURCE_TYPE_CONFIG: Record<SourceType, { cls: string; description: string; icon: string }> = {
  'Salesforce Knowledge':  { cls: 'text-[#2F6F7E] bg-[#EDF5F8] border-[#7FAFC6]',          description: 'Knowledge articles published in Salesforce Knowledge',                        icon: 'database'       },
  'Google Drive':          { cls: 'text-[#2F6B3F] bg-[#E6F0EA] border-[#9FC3AE]',        description: 'Program folders, coach guides, and resources in Google Drive',               icon: 'folder-open'    },
  'LMS Content':           { cls: 'text-[#CC8400] bg-[#FFF3E0] border-[#FFD08A]',        description: 'Module and lesson content delivered through the LMS platform',               icon: 'graduation-cap' },
  'Assessments':           { cls: 'text-[#2F6F7E] bg-[#EDF5F8] border-[#7FAFC6]',     description: 'Assessment questions, results, and scoring data',                            icon: 'check-square'   },
  'Standards Studio':      { cls: 'text-[#A93F2F] bg-[#FBEAE6] border-[#E8B9B4]',           description: 'Content quality rules and Penny prompt standards defined in Standards Studio', icon: 'shield-check' },
  'Curriculum Studio':     { cls: 'text-[#CC8400] bg-[#FFF3E0] border-[#FFD08A]',     description: 'Module outlines, lesson templates, and Penny curriculum assets',             icon: 'layers'         },
  'Penny Generated':       { cls: 'text-secondary border-secondary/20 bg-secondary/10', description: 'Content and logs generated by Penny: coaching messages, reflections, summaries', icon: 'brain'       },
  'Slack History':         { cls: 'text-slate-700 bg-slate-50 border-slate-200',        description: 'Future: Slack conversation history from coaching threads and cohort channels', icon: 'message-square' },
  'Google Chat History':   { cls: 'text-slate-700 bg-slate-50 border-slate-200',        description: 'Future: Google Chat conversation history from program spaces',               icon: 'message-circle' },
  'Calendar Events':       { cls: 'text-cyan-700 bg-cyan-50 border-cyan-200',           description: 'Future: Google Calendar event data for session context and sprint tracking', icon: 'calendar'       },
};

export const TRUST_LEVEL_CONFIG: Record<TrustLevel, { cls: string; description: string; order: number }> = {
  'Authoritative': { cls: 'text-[#2F6B3F] bg-[#E6F0EA] border-[#9FC3AE]', description: 'Single source of truth. Penny treats this as ground truth with no override.', order: 1 },
  'Trusted':       { cls: 'text-[#2F6F7E] bg-[#EDF5F8] border-[#7FAFC6]',   description: 'Vetted and reviewed. Penny uses without additional validation.',              order: 2 },
  'Curated':       { cls: 'text-[#CC8400] bg-[#FFF3E0] border-[#FFD08A]', description: 'Human-reviewed subset. Penny uses but flags as curated.',                    order: 3 },
  'Unverified':    { cls: 'text-[#A93F2F] bg-[#FBEAE6] border-[#E8B9B4]',   description: 'Not yet reviewed. Penny should not use without explicit approval.',          order: 4 },
};

export const SYNC_STATUS_CONFIG: Record<SyncStatus, { cls: string; label: string }> = {
  'Live':         { cls: 'text-[#2F6B3F] bg-[#E6F0EA] border-[#9FC3AE]',    label: 'Live Sync'     },
  'Manual':       { cls: 'text-[#CC8400] bg-[#FFF3E0] border-[#FFD08A]',    label: 'Manual Update' },
  'Disconnected': { cls: 'text-[#A93F2F] bg-[#FBEAE6] border-[#E8B9B4]',       label: 'Disconnected'  },
  'Planned':      { cls: 'text-[#2F6F7E] bg-[#EDF5F8] border-[#7FAFC6]', label: 'Planned'       },
  'Future':       { cls: 'text-slate-500 bg-slate-50 border-slate-200',    label: 'Future'        },
};

export const HEALTH_CONFIG: Record<HealthStatus, { cls: string; dotCls: string }> = {
  'Healthy':  { cls: 'text-[#2F6B3F] bg-[#E6F0EA] border-[#9FC3AE]', dotCls: 'bg-[#2F6B3F]' },
  'Warning':  { cls: 'text-[#CC8400] bg-[#FFF3E0] border-[#FFD08A]', dotCls: 'bg-[#FFF3E0]0' },
  'Critical': { cls: 'text-[#A93F2F] bg-[#FBEAE6] border-[#E8B9B4]',   dotCls: 'bg-[#FBEAE6]0'  },
  'Future':   { cls: 'text-slate-500 bg-slate-50 border-slate-200', dotCls: 'bg-slate-300' },
};

// ── Document Category Taxonomy ─────────────────────────────────────────────

export const DOCUMENT_CATEGORY_TAXONOMY: { id: string; label: string; color: string }[] = [
  { id: 'technology',       label: 'Technology',        color: 'bg-[#EDF5F8] text-[#2F6F7E] border-[#7FAFC6]'         },
  { id: 'mission-delivery', label: 'Mission & Delivery', color: 'bg-[#E6F0EA] text-[#2F6B3F] border-[#9FC3AE]' },
  { id: 'curriculum',       label: 'Curriculum',         color: 'bg-[#FFF3E0] text-[#CC8400] border-[#FFD08A]'       },
  { id: 'assessments',      label: 'Assessments',        color: 'bg-[#EDF5F8] text-[#2F6F7E] border-[#7FAFC6]'    },
  { id: 'operations',       label: 'Operations',         color: 'bg-slate-50 text-slate-700 border-slate-200'       },
  { id: 'research',         label: 'Research',           color: 'bg-[#FBEAE6] text-[#A93F2F] border-[#E8B9B4]'          },
  { id: 'communications',   label: 'Communications',     color: 'bg-[#E6F0EA] text-[#2F6B3F] border-[#9FC3AE]'          },
  { id: 'resources',        label: 'Resources',          color: 'bg-[#FFF3E0] text-[#CC8400] border-[#FFD08A]'    },
];

// ── SF Knowledge Category Taxonomy ─────────────────────────────────────────

export const SF_KNOWLEDGE_CATEGORIES = [
  {
    id: 'mission-delivery',
    name: 'Mission & Delivery',
    description: 'Program models, organizational mission, coaching delivery standards, learner pathways, and program-specific content.',
    subcategories: ['Program Model', 'Coaching Delivery', 'Learner Pathways', 'Career Outcomes', 'Participant Guidelines'],
  },
  {
    id: 'operations-business',
    name: 'Operations & Business',
    description: 'Internal operational processes, business policies, staffing, finance, and partner management.',
    subcategories: ['Internal Operations', 'Business Policies', 'Partner Management', 'Staff Onboarding', 'Compliance'],
  },
  {
    id: 'technology-trail-os',
    name: 'Technology & Trail OS',
    description: 'Salesforce platform how-tos, Trail OS documentation, system configuration, and technical standards.',
    subcategories: ['Salesforce Platform', 'Trail OS', 'System Configuration', 'Integration Guides', 'Data Model'],
  },
];

// ── Source ordering ─────────────────────────────────────────────────────────

export const SOURCE_TYPE_ORDER: SourceType[] = [
  'Salesforce Knowledge', 'Google Drive', 'LMS Content', 'Assessments',
  'Standards Studio', 'Curriculum Studio', 'Penny Generated',
  'Slack History', 'Google Chat History', 'Calendar Events',
];

// ── Runtime data ────────────────────────────────────────────────────────────
// Data is API-backed via GET /api/knowledge/sources → useKnowledgeSources().
// This empty export keeps any legacy compile-time imports valid.
export const knowledgeSources: KnowledgeSource[] = [];
