import { useAppContext } from '@/context/AppContext';
import { commBroadcasts, type CommBroadcast } from '@/data/commData';
import { Badge } from '@/components/ui/badge';
import { Sparkles, Bell, ChevronRight } from 'lucide-react';

const TYPE_COLORS: Record<CommBroadcast['type'], string> = {
  reminder:     'bg-sky-50 text-sky-800 border-sky-200',
  prompt:       'bg-purple-50 text-purple-800 border-purple-200',
  nudge:        'bg-amber-50 text-amber-800 border-amber-200',
  announcement: 'bg-emerald-50 text-emerald-800 border-emerald-200',
  celebration:  'bg-pink-50 text-pink-800 border-pink-200',
};

const TYPE_LABELS: Record<CommBroadcast['type'], string> = {
  reminder: 'Reminder', prompt: 'Prompt', nudge: 'Nudge', announcement: 'Announcement', celebration: 'Celebration',
};

function statusBadge(status: CommBroadcast['status']) {
  if (status === 'active')  return <Badge className="text-[10px] bg-green-50 text-green-800 border-green-200 border">Active</Badge>;
  if (status === 'planned') return <Badge className="text-[10px] bg-primary/10 text-primary border-primary/20 border">Planned</Badge>;
  return <Badge variant="secondary" className="text-[10px]">Draft</Badge>;
}

export default function PennyBroadcasts() {
  const { setSelectedItem } = useAppContext();

  function select(b: CommBroadcast) {
    setSelectedItem({ type: 'commBroadcast', id: b.id, data: b });
  }

  return (
    <div className="h-full overflow-y-auto p-6 bg-muted/20">
      <div className="max-w-4xl mx-auto space-y-8">

        <div>
          <p className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground/50 mb-1">Communications</p>
          <h1 className="text-3xl font-bold text-foreground">Penny Broadcasts</h1>
          <p className="text-muted-foreground mt-2 leading-relaxed max-w-2xl">
            Automated messages Penny sends to learners, coaches, and cohorts — triggered by Trail OS events. Click any broadcast to open its Knowledge Brief.
          </p>
        </div>

        <div className="rounded-md bg-secondary/10 border border-secondary/20 px-4 py-3 flex items-start gap-2">
          <Sparkles className="w-4 h-4 text-secondary mt-0.5 shrink-0" />
          <p className="text-[11px] text-secondary/90 leading-relaxed">
            <strong>Penny composes all broadcasts.</strong> The message content is generated by Penny using the template as a scaffold — personalised with learner name, program, and relevant context at send time. Broadcasts are not static messages.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-4">
          {commBroadcasts.map(b => (
            <button
              key={b.id}
              onClick={() => select(b)}
              className="rounded-xl border border-border bg-white shadow-sm p-5 text-left hover:border-primary/30 hover:shadow-md transition-all group flex flex-col gap-3"
            >
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-center gap-2">
                  <Bell className="w-4 h-4 text-secondary shrink-0" />
                  <span className="font-bold text-foreground text-sm">{b.name}</span>
                </div>
                <div className="flex flex-col items-end gap-1 shrink-0">
                  {statusBadge(b.status)}
                </div>
              </div>

              <div className="flex flex-wrap gap-1.5">
                <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${TYPE_COLORS[b.type]}`}>{TYPE_LABELS[b.type]}</span>
                <span className="text-[10px] px-2 py-0.5 rounded-full border border-border bg-muted text-muted-foreground">{b.frequency}</span>
              </div>

              <div className="space-y-1">
                <p className="text-[10px] font-semibold text-muted-foreground/60 uppercase tracking-wider">Trigger</p>
                <p className="text-[11px] text-muted-foreground">{b.trigger}</p>
              </div>

              <p className="text-[11px] text-muted-foreground leading-relaxed line-clamp-2">{b.purpose}</p>

              <div className="bg-muted/50 rounded-md px-3 py-2 border border-border/40">
                <p className="text-[10px] font-semibold text-muted-foreground/60 uppercase tracking-wider mb-1">Example Message</p>
                <p className="text-[10px] text-muted-foreground leading-relaxed italic line-clamp-2">{b.example}</p>
              </div>

              <div className="flex items-center gap-1 text-[10px] text-primary/60 group-hover:text-primary transition-colors mt-auto">
                <ChevronRight className="w-3 h-3" />
                <span>Open Trail Insights</span>
              </div>
            </button>
          ))}
        </div>

        <div className="rounded-xl border border-border/60 bg-muted/30 px-5 py-4">
          <p className="text-[11px] text-muted-foreground leading-relaxed">
            <strong>Prototype mode —</strong> No broadcasts are live. Broadcasts will fire through the Slack adapter when provider connections are established. Configuration managed in Administration → Comm Channels.
          </p>
        </div>

      </div>
    </div>
  );
}
