import { Router, type IRouter } from "express";
import healthRouter          from "./health";
import slackRouter           from "./slack";
import secretsRouter         from "./secrets";
import geminiRouter          from "./gemini";
import googleRouter          from "./google";
import googleOAuthRouter     from "./googleOAuth";
import salesforceRouter      from "./salesforce";
import salesforceAuthRouter  from "./salesforceAuth";
import pennyDataRouter       from "./pennyData";
import pennyRouter           from "./penny";
import retrieveRouter        from "./retrieve";
import calendarRouter        from "./calendar";
import gmailRouter           from "./gmail";
import agentforceRouter      from "./agentforce";
import authRouter            from "./auth";
import googleGroupsRouter    from "./googleGroups";
import driveRouter           from "./drive";
import notificationsRouter   from "./notifications";
import learnerAuthRouter      from "./learnerAuth";
import learnerRouter          from "./learner";
import promptTemplatesRouter  from "./promptTemplates";
import promptVariablesRouter  from "./promptVariables";
import programsRouter          from "./programs";
import knowledgeRouter         from "./knowledge";

const router: IRouter = Router();

router.use("/auth/salesforce", salesforceAuthRouter);
router.use("/penny/data", pennyDataRouter);
router.use(healthRouter);
router.use(slackRouter);
router.use(secretsRouter);
router.use(geminiRouter);
router.use(googleRouter);
router.use(googleOAuthRouter);
router.use(salesforceRouter);
router.use(pennyRouter);
router.use(retrieveRouter);
router.use(calendarRouter);
router.use(gmailRouter);
router.use(agentforceRouter);
router.use(authRouter);
router.use(googleGroupsRouter);
router.use(driveRouter);
router.use(notificationsRouter);
router.use(learnerAuthRouter);
router.use(learnerRouter);
router.use(promptTemplatesRouter);
router.use(promptVariablesRouter);
router.use(programsRouter);
router.use(knowledgeRouter);

export default router;
