// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/collab-overview/CommandCenter.tsx": () => import("../components/mockups/collab-overview/CommandCenter.tsx"),
  "./components/mockups/gmail-page/OptionA.tsx": () => import("../components/mockups/gmail-page/OptionA.tsx"),
  "./components/mockups/gmail-page/OptionB.tsx": () => import("../components/mockups/gmail-page/OptionB.tsx"),
  "./components/mockups/gmail-panel/InboxHybrid.tsx": () => import("../components/mockups/gmail-panel/InboxHybrid.tsx"),
  "./components/mockups/gmail-panel/InboxSummary.tsx": () => import("../components/mockups/gmail-panel/InboxSummary.tsx"),
  "./components/mockups/gmail-panel/QuickCompose.tsx": () => import("../components/mockups/gmail-panel/QuickCompose.tsx"),
  "./components/mockups/integration-hub/OptionA.tsx": () => import("../components/mockups/integration-hub/OptionA.tsx"),
  "./components/mockups/integration-hub/OptionB.tsx": () => import("../components/mockups/integration-hub/OptionB.tsx"),
  "./components/mockups/integration-hub/OptionC.tsx": () => import("../components/mockups/integration-hub/OptionC.tsx"),
  "./components/mockups/penny-assets-v1/StatePicker.tsx": () => import("../components/mockups/penny-assets-v1/StatePicker.tsx"),
  "./components/mockups/penny-assets-v2/TwoPanel.tsx": () => import("../components/mockups/penny-assets-v2/TwoPanel.tsx"),
  "./components/mockups/penny-config-a/GuidedMissionTrail.tsx": () => import("../components/mockups/penny-config-a/GuidedMissionTrail.tsx"),
  "./components/mockups/penny-config-b/InlineCopilotWorkshop.tsx": () => import("../components/mockups/penny-config-b/InlineCopilotWorkshop.tsx"),
  "./components/mockups/penny-config-b/SetupProcessWorkshop.tsx": () => import("../components/mockups/penny-config-b/SetupProcessWorkshop.tsx"),
  "./components/mockups/people-access/OptionA.tsx": () => import("../components/mockups/people-access/OptionA.tsx"),
  "./components/mockups/people-access/OptionB.tsx": () => import("../components/mockups/people-access/OptionB.tsx"),
  "./components/mockups/people-access/OptionC.tsx": () => import("../components/mockups/people-access/OptionC.tsx"),
  "./components/mockups/penny-config-c/ProgressiveSkillTree.tsx": () => import("../components/mockups/penny-config-c/ProgressiveSkillTree.tsx")
};
